name: Reusable workflow

on:
  workflow_call:
    outputs:
      matrix:
        description: Matrix
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        shell: bash
        run: |
          {
            echo 'matrix<<EOF'
            cat "$MATRIX_JSON"
            echo EOF
          } | tee /dev/stderr >> "$GITHUB_OUTPUT"
        env:
          MATRIX_JSON: /home/runner/work/_actions/julianbrost/test-actions-set-matrix-output/main/matrix.json
