name: Reusable workflow

on:
  workflow_call:
    outputs:
      matrix:
        description: Matrix
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        uses: julianbrost/test-actions-set-matrix-output@main
      - id: find
        shell: bash
        run: find / -xdev -name matrix.json
